# DEPRECATED
# TODO: Update as necessary or remove

# function md_concat_lines(
#         paths::Vector{<:AbstractString};
#         cfg = ContextBundler.load_config(),
#         sortpaths = true,
#         log::Bool = true,
#     )

#     if sortpaths
#         paths = sort(paths)
#     end

#     # --- Read config values with defaults ---
#     heading_level = get(cfg, "separator.heading.level", 2)
#     missing_mode  = get(cfg, "missing", "error")

#     # One-shot run header
#     log && @info "Concatenating files." files=length(paths) heading_level=heading_level on_missing=missing_mode

#     # --- relnames prefix ---
#     prefix = common_prefix(paths)
#     relnames = Dict{String, String}()
#     for path in paths
#         relname = replace(path, prefix => "")
#         relname = strip(relname, '/')
#         relnames[path] = relname
#     end

#     # --- Globals ---
#     md_concat_lines = String[]
#     heading = repeat("#", heading_level)

#     # --- Prepare output file ---
#     timestamp = Dates.format(now(), dateformat"yyyy-mm-dd HH:MM:SS")
#     push!(md_concat_lines, "<!-- Generated by ContextBundler.jl at $timestamp -->")
#     push!(md_concat_lines, "")

#     # --- Table of content ---
#     push!(md_concat_lines, "***")
#     push!(md_concat_lines, "$heading TABLE OF CONTENTS")
#     push!(md_concat_lines, "")
#     for (pi, path) in enumerate(paths)
#         relname = relnames[path]
#         push!(md_concat_lines, "$(pi). [Content of '$(relname)'](#sc-$(pi))")
#     end

#     # --- Add files ---
#     for (pi, path) in enumerate(paths)
#         if !isfile(path)
#             msg = "File not found: $path"
#             if missing_mode == "warn_skip"
#                 log && @warn msg
#                 continue
#             else
#                 error(msg)
#             end
#         end

#         # --- Header separator ---
#         push!(md_concat_lines, "\n")
#         push!(md_concat_lines, "***")
#         relname = relnames[path]
#         push!(md_concat_lines, "<!-- ANCHOR: sc-$(pi) -->")
#         push!(md_concat_lines, "$heading $pi [[$(relname)]]")
#         push!(md_concat_lines, "")

#         # --- Append file content ---
#         push!(md_concat_lines, "<!-- START CONTENT OF FILE: SRC: path=\"$relname\" -->")
#         try
#             lang = _getlang(path)
#             push!(md_concat_lines, "`````````$(lang)")
#             for line in eachline(path; keep=false)
#                 push!(md_concat_lines, line)
#             end
#             push!(md_concat_lines, "`````````")
#         catch e
#             log && @warn "Error reading $relname: $e"
#         end
#         push!(md_concat_lines, "<!-- END CONTENT: SRC: path=\"$relname\" -->")

#         # --- Blank lines between sections ---
#         push!(md_concat_lines, "\n")
#     end

#     return md_concat_lines
# end
